name: MCwarp
main: mocha.plugin.mc.MCwarp
author: mocha
version: 1.1-release
api: [1.0.0]
website: https://github.com/moca127/MOCHA-EULA/blob/master/LICENSE.md

commands : 
 워프추가 : 
  permission : mocha.plugin.addwarp.cmd
  default : OP
  description : "워프를 추가합니다."
  aliases : ["addwarp", "warpadd"]
 워프삭제 : 
  permission : mocha.plugin.delwarp.cmd
  default : OP
  description : "워프를 삭제합니다."
  aliases : ["delwarp","warpdel"]
 워프 : 
  permission : mocha.plugin.warp.cmd
  default : true
  description : "워프합니다."
  aliases : ["warp","이동"]
  
permissions : 
 mocha.plugin.addwarp.cmd : 
  default : OP
 mocha.plugin.delwarp.cmd : 
  default : OP
 mocha.plugin.warp.cmd : 
  default : true